springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /swagger-ui.html
server:
  port: 8080
spring:
  application:
    name: mongo-db-enc-custom

spring.data.mongodb.host: localhost
spring.data.mongodb.port: 27017
spring.data.mongodb.database: failed-payload
# Or use a full connection URI:
spring.data.mongodb.uri: mongodb://localhost:27017/failed-payload

